# Use official Java 17 image as base image
FROM openjdk:17-jdk-alpine

# Set working directory
WORKDIR /app

# Copy the packaged jar file into the container
COPY ./*.jar /app.jar

# Expose port 8080
EXPOSE 8080 

# Run the jar file when the container starts
CMD java -jar /app.jar