name: Build & Deploy Spring Back-End

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - name: Step 1 checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Step 2 Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'corretto'
                java-version: '17'
            - name: Step 3 Test
              run: mvn test

            - name: step 4 SonarQube Scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: mvn sonar:sonar -Dsonar.host.url=https://0d4a-145-93-40-139.ngrok-free.app/sessions/new?return_to=%2F -Dsonar.projectKey=OrangeJonathan_S3DB-IP-PokemonRace-BackEnd_AYvcPE-nwIL5ZJDQv0UG

            - name: Step 5 Build with Maven
              run: mvn -B package --file pom.xml

    

    build-and-push-docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2 
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          
        - name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile.ci
            push: true
            tags: orangeplayah/s3db-ip-pokemonrace-backend:latest 
    