name: Build & Deploy Spring Back-End

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    build-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Step-1 checkout
              uses: actions/checkout@v2

            - name: Step-2 One-Line script test
              run: echo "Hello World" 

            - name: Step-3 Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'corretto'
                java-version: '17'
        
            - name: Step-4 Build with Maven
              run: mvn -B package --file pom.xml