name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    sonarqube-check:
        name: SonarQube Check
        runs-on: ubuntu-latest
        permissions: read-all
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'corretto'
                java-version: '17'

            - name: SonarQube Scan
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              run: mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.projectKey=${{ secrets.SONAR_TOKEN }}